services:
  booking-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pensionat_db
      MYSQL_USER: booking_user
      MYSQL_PASSWORD: booking_password


  customer-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pensionat_db
      MYSQL_USER: customer_user
      MYSQL_PASSWORD: customer_password


  booking-service:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - customer-db

  customer-service:
    build: ../b2_pensionat_customer
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"
    depends_on:
      - booking-db
