spring.application.name=backend1
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:10.0.6.21}:3306/pensionat_db
spring.datasource.username=dbUser512
spring.datasource.password=WIRd0Dinda65RjUWtq8t5AbTiIGlORVbDIClIhpVgTgZerPuV6